name: MAS Installer Workflow

on:
  workflow_dispatch:  # Allow manual triggering
  # Uncomment and modify as needed for automatic triggers
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GitHub CLI
      run: |
        # Install GitHub CLI
        choco install gh -y
      shell: powershell

    - name: Download MasInstaller.exe
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Explicitly set repository details
        $repoOwner = "Mon1-innovation"
        $repoName = "MASToolScript"

        try {
          # Use GitHub CLI to get releases with better error handling
          $releases = gh release list -R "$repoOwner/$repoName" --json tagName,assets --limit 1

          # Parse the JSON response
          $releaseInfo = $releases | ConvertFrom-Json
          $installerAsset = $releaseInfo.assets | Where-Object { $_.name -eq "MasInstaller.exe" }

          if ($installerAsset) {
            # Download the installer
            gh release download -R "$repoOwner/$repoName" -p "MasInstaller.exe"

            # Verify file exists
            if (Test-Path "MasInstaller.exe") {
              Write-Host "Successfully downloaded MasInstaller.exe"
            } else {
              throw "Download failed: MasInstaller.exe not found"
            }
          } else {
            throw "No MasInstaller.exe found in the latest release"
          }
        } catch {
          Write-Error "Failed to download MasInstaller.exe: $_"
          exit 1
        }
      shell: pwsh

    - name: Create Installation Directory
      run: |
        New-Item -ItemType Directory -Path .\MAS_Install
        Move-Item -Path MasInstaller.exe -Destination .\MAS_Install\
      shell: powershell

    - name: Run MasInstaller.exe
      run: |
        Set-Location .\MAS_Install
        Start-Process -FilePath .\MasInstaller.exe -Wait -ArgumentList @('', '', '', '', '', '', '', '')
      shell: powershell

    - name: Upload Installation Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MAS-Installation
        path: .\MAS_Install\*
        retention-days: 5